const APIconfig = {
    apiKey: 'eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI3ZGI4NDAzNDMxYzU3NjAxYWJiNzc1OTJlNDU2NGE5YiIsInN1YiI6IjY0OTQwODVmY2ZlNDhmMDBjNmZhNzcyZiIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.fOqKYgze0HEhyKE_cSkVZYIV2QI4yHiVYwunbGJTEW0'
}

export default APIconfig;